### ISSUE TITLE
Unresolved Exception

### ISSUE THREAD

**Issue by DamiSang** [Dyvinia/DatapathFixPlugin#10]
I keep getting a "unhandled exception" error saying that the application is already being used in another process. I am admittedly fairly new to modding EA titles, so it may be something I'm doing on my end, but I've tried running the process in administrator mode which is the only fix I can think of and not even that worked. The game is Mass Effect: Andromeda.

**Comment by DamiSang** [comment]
The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Mass Effect Andromeda\CryptBase.dll' because it is being used by another process.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Frosty.ModSupport.FrostyModExecutor.CopyFileIfRequired(String source, String dest)
   at Frosty.ModSupport.FrostyModExecutor.Run(FileSystem inFs, CancellationToken cancelToken, ILogger inLogger, String rootPath, String modPackName, String additionalArgs, String[] modPaths)
   at FrostyModManager.MainWindow.<>c__DisplayClass14_0.<launchButton_Click>b__0(FrostyTaskWindow task)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.Core.Windows.FrostyTaskWindow.<FrostyTaskWindow_Loaded>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   
   (The full error, if this helps.)

**Comment by Dyvinia** [comment]
afaik thats not related to datapathfix
