### ISSUE TITLE
"Field not found" error

### ISSUE THREAD

**Issue by ShotgunsAndSass** [Dyvinia/DatapathFixPlugin#16]
`Field not found: 'Frosty.Core.App.FileSystemManager'.

   at DatapathFixPlugin.Actions.LaunchExecutionAction.<get_PreLaunchAction>b__8_0(ILogger logger, PluginManagerType type, CancellationToken cancelToken)
   at FrostyModManager.MainWindow.<>c__DisplayClass14_0.<launchButton_Click>b__0(FrostyTaskWindow task)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.Core.Windows.FrostyTaskWindow.<FrostyTaskWindow_Loaded>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by Dyvinia** [comment]
You are using the wrong version of dpfix
