### ISSUE TITLE
Bug with NFS Payback, Unsure of Other Games (DatapathFix v1.5.1)

### ISSUE THREAD

**Issue by boiUneedAwash** [Dyvinia/DatapathFixPlugin#18]
See Here: https://discord.com/channels/740960805876531200/1112970379565203518/1112970379565203518

Copy Paste:

My game is on Steam, C:\ Drive Library. Current Game I'm trying to play is NFS Payback. Both the 107 version (obviously: Frosty 1.0.6.2) AND regular version were not working for me with NFS Payback. Errors include the "Field not found" error (even when using the correct version) As well as: 'This game is on a different account' error. And in general the game just not launching. Fiddling with different launch options in Frosty Mod Manager did not fix this. If anybody is having similar issues, here's how I fixed it: Use DatapathFix v1.5.0 in the previous releases for now and turn off 'Check for updates' under Tools > Options > DatapathFix Options > "Check for updates"  

Launch options in Frosty MM Options were not necessary for me to get DatapathFix 1.5.0 working. Depending on your platform however your mileage may vary.

This is as of 4:43pm 30th of May 2023 (UTC+12:00) Auckland Wellington

Hope this helps some of you!

![other error 151](https://github.com/Dyvinia/DatapathFixPlugin/assets/37860709/a980ceb5-ca32-421a-9dd0-cbe7a4396e05)
![Github](https://github.com/Dyvinia/DatapathFixPlugin/assets/37860709/f059d18a-44d4-4636-ab8a-09a81eb65361)

Field not found: 'Frosty.Core.App.FileSystemManager'.

   at DatapathFixPlugin.Actions.LaunchExecutionAction.<get_PreLaunchAction>b__8_0(ILogger logger, PluginManagerType type, CancellationToken cancelToken)
   at FrostyModManager.MainWindow.<>c__DisplayClass14_0.<launchButton_Click>b__0(FrostyTaskWindow task)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.Core.Windows.FrostyTaskWindow.<FrostyTaskWindow_Loaded>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by boiUneedAwash** [comment]
Closed. Steam X EA was creating the .orig.exe issue. I may have left in the incorrect files or not hit ctrl v. I apologies for the issue. Please ignore this

**Comment by McNuggies5** [comment]
how did you fix this?
