### ISSUE TITLE
An Unhandled Exception Has Occurred

### ISSUE THREAD

**Issue by McNuggies5** [Dyvinia/DatapathFixPlugin#20]
When I try launching the game with the plugin I get this message:

An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at FrostySdk.Managers.AssetManager.ReadFromCache(List`1& prePatchCache)
   at FrostySdk.Managers.AssetManager.Initialize(Boolean additionalStartup, AssetManagerImportResult result)
   at Frosty.ModSupport.FrostyModExecutor.Run(FileSystem inFs, CancellationToken cancelToken, ILogger inLogger, String rootPath, String modPackName, String additionalArgs, String[] modPaths)
   at FrostyModManager.MainWindow.<>c__DisplayClass14_0.<launchButton_Click>b__0(FrostyTaskWindow task)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.Core.Windows.FrostyTaskWindow.<FrostyTaskWindow_Loaded>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Dyvinia** [comment]
seems to be a normal frosty issue, rather than something relating to dpfix
