### ISSUE TITLE
im unsure whats happening but im getting this after extracting the datapathfix folders to plugins

### ISSUE THREAD

**Issue by ben9120** [Dyvinia/DatapathFixPlugin#21]
Field not found: 'Frosty.Core.App.FileSystem'.

   at DatapathFixPlugin.Actions.LaunchExecutionAction.<get_PreLaunchAction>b__8_0(ILogger logger, PluginManagerType type, CancellationToken cancelToken)
   at FrostyModManager.MainWindow.<>c__DisplayClass16_0.<launchButton_Click>b__0(FrostyTaskWindow task)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.Core.Windows.FrostyTaskWindow.<FrostyTaskWindow_Loaded>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Dyvinia** [comment]
wrong version, use normal download for frosty 1.0.6.x and 107 for 1.0.7.x
